#!/bin/bash

./stop_app

LARAVEL_APP_PATH="./blogs"
NODE_APP_PATH="./editor"

export APP_PORT=8000

echo "Creating application network if doesn't exist..."
docker network inspect blogs_app > /dev/null 2>&1
if [ $? -ne 0 ]; then
    docker network create blogs_app || { echo "Failed to create network"; exit 1; }
fi

# Spin up Laravel app
echo "Starting Laravel application..."
cd $LARAVEL_APP_PATH || { echo "Failed to change directory to $LARAVEL_APP_PATH"; exit 1; }

echo "check composer packages..."
composer update || { echo "Failed to change directory to $LARAVEL_APP_PATH"; exit 1; }

echo "Starting Laravel application..."
./vendor/bin/sail up -d --build || { echo "Failed to start Laravel application"; exit 1; }

echo "Installing Node packages..."
./vendor/bin/sail npm install || { echo "Failed to build Laravel assets"; exit 1; }

echo "Building Laravel assets..."
./vendor/bin/sail npm run build || { echo "Failed to build Laravel assets"; exit 1; }

echo "Running Laravel migrations..."
./vendor/bin/sail artisan migrate || { echo "Failed to run Laravel migrations"; exit 1; }

echo "Running Laravel seeders..."
./vendor/bin/sail artisan db:seed || { echo "Failed to run Laravel seeders"; exit 1; }

cd - || { echo "Failed to return to the initial directory"; exit 1; }

# Spin up Node.js app
echo "Starting Node.js application..."
docker-compose -f $NODE_APP_PATH/docker-compose.yml up -d --build || { echo "Failed to start Node.js application"; exit 1; }

echo "Starting other components..."
docker-compose up -d --build

echo "Starting Laravel Redis subscriber..."
cd $LARAVEL_APP_PATH || { echo "Failed to change directory to $LARAVEL_APP_PATH"; exit 1; }
nohup ./vendor/bin/sail artisan app:redis-sub > /dev/null 2>&1 &

echo "All services started successfully."
