openapi: 3.0.0
info:
  title: Coronatime API
  description: Here goes description
  version: 0.1.9

servers:
  - url: http://blogs.demo/api
    description: local server
  - url: https://blogs-prototype.mohamedaymn.site/api
    description: production server

paths:
  /posts:
    get:
      summary: Returns a list of posts.
      responses:
        '200': 
          description: A JSON array posts
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string